version: '3.7'

services:
  postgres:
    image: postgres:13.0
    ports:
      - '1432:1432'
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: db
      POSTGRES_PASSWORD: password

  minio:
    image: minio/minio:RELEASE.2021-03-17T02-33-02Z
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: key
      MINIO_SECRET_KEY: secret1337
    command: 'minio server /export'
