version: '3.7'

services:
  postgres:
    image: postgres:13.0
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: db
      POSTGRES_PASSWORD: password

  minio:
    image: minio/minio:RELEASE.2020-08-18T19-41-00Z
    ports:
      - 1337:9000
    environment:
      MINIO_ACCESS_KEY: key
      MINIO_SECRET_KEY: secret1337
    command: 'minio server /export'
